server:
  port: 8082

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600

      routes:
        - id: lab-results-service
          uri: lb://lab-results-service
          predicates:
            - Path=/lab-results/**
          filters:
            - StripPrefix=1

        - id: prescriptions-service
          uri: lb://prescriptions-service
          predicates:
            - Path=/prescriptions/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info